### ISSUE TITLE
Option to skip songs

### ISSUE THREAD

**Issue by Installieren** [Founntain/osuplayer-issues#5] opened 2020-10-27 17:42 UTC
**What do you would like to see in the player?**
An option to skip songs with the same name.

**How would you like to see the feature? E.g. the way implemented or displayed**
A taggable option within the main players settings.

**Additional context**
I have to skip more then once, do to PP Mapping giving us so maybe times the same songs. Would be nice.

**Comment by Founntain** [comment] 2020-10-27 17:44
Duplicate of #4

**Closed by Founntain** 2020-10-27 17:44 UTC
Labels: duplicate
