### ISSUE TITLE
Repeat Button in Miniplayer

### ISSUE THREAD

**Issue by Installieren** [Founntain/osuplayer-issues#10] opened 2020-10-31 00:25 UTC
**Your osu!player username**
Login

**Describe the bug**
Repeat Song button doen't work in Miniplayer

**Expected behavior**
It should repeat the song.

**Additional context**
Running version v74

**Comment by Founntain** [comment] 2020-11-11 20:57
Works as intended: (Click is hard to see tho, but repeats the song) https://x.founntain.de/xObR5XXI.mp4

**Comment by Founntain** [comment] 2020-11-11 21:03
Merged with #11

**Closed** 2020-11-11 21:03 UTC
Labels: bug
