### ISSUE TITLE
Repeat not working when "Skip song with same name" is enabled

### ISSUE THREAD

**Issue by Installieren** [Founntain/osuplayer-issues#11] opened 2020-11-11 20:53 UTC
**Your osu!player username**
Login

**Describe the bug**
Title

**Expected behavior**
It should Repeat the song with the button turned on, but it doesn't.

**Additional context**
Running v74

**Comment by Founntain** [comment] 2020-11-11 20:56
Works as intended: https://x.founntain.de/TZCt31eD.mp4

**Comment by Installieren** [comment] 2020-11-11 21:01
Wearend ich "Ueberspringe namen mit selben song" an habe geht der Repeat button nicht mehr.

**Comment by Founntain** [comment] 2021-01-12 09:14
Fixed in new version

**Closed by Founntain** 2021-01-12 09:14 UTC
Labels: bug
